### PR TITLE
Update jekyll and ruby/remove SASS `mixed-decls`

### PR DESCRIPTION
**Pull request by rgarner**
- Update to Ruby 3.3.5 (hey, it'll be the same as JT for 5...4...3....)
- Fix all the `mixed-decls` warnings (this is [hell](https://github.com/sass/dart-sass/issues/2276), [but](https://github.com/sass/dart-sass/issues/2276#issuecomment-2221796821))
- Update to Jekyll 4.3.4 (just to stay current, this brings another warning with the update to sass-embedded 1.79.x)

### CODE REVIEW

**Comment by tekin** [comment]
Looks like we've lost some font weighting on the home page headings:

## Old version

old

vs

## New version

new

**Comment by rgarner** [comment]
Ah, and indeed, piss.

**Comment by rgarner** [comment]
Going to have to do it again, from the start. Originally I did it with the 50-odd warnings one warning at a time; looks like I'll have to do it with a second monitor on refresh too

**Review by tekin — APPROVED** [review]
Cool beans 😎

**Pull request merged**
